### ISSUE TITLE
Club icons not displayed properly (Android)

### ISSUE THREAD

**Issue by pohzhiee** [NottsCSS/NottCS#32]
![image](https://user-images.githubusercontent.com/22704923/38236837-fc77a96e-3757-11e8-944d-da756bd2d603.png)

UWP works fine

**Comment by jiamingc0824** [comment]
UWP using diff Nuget package.
Will fix soon.

**Comment by pohzhiee** [comment]
fixed after change to using image from web, also scaled properly
