### ISSUE TITLE
CreateEventPage settings button not navigating properly

### ISSUE THREAD

**Issue by pohzhiee** [NottsCSS/NottCS#34]
Now it navigates to some form.

Side note: CreateEventPage also has no title

**Comment by jiamingc0824** [comment]
Any image?

**Comment by pohzhiee** [comment]
it goes to the event sign up registration form

**Comment by jiamingc0824** [comment]
Its not happening on my side. Are u doing smth wrongly?

**Comment by pohzhiee** [comment]
Settings iconsupposed to be a + icon LOL

**Comment by jiamingc0824** [comment]
Closed
