### ISSUE TITLE
Exception thrown upon JSON serializing

### ISSUE THREAD

**Issue by jiamingc0824** [NottsCSS/NottCS#35]
![image](https://user-images.githubusercontent.com/33931383/38249381-0c661704-377e-11e8-83bd-c8883905300a.png)

**Comment by jiamingc0824** [comment]
System.Reflection.CustomAttributeFormatException: Could not find a property with name ItemNullValueHandling

**Comment by jiamingc0824** [comment]
If you serialize EventAdditionalParameter, the exception above will throw.

**Comment by pohzhiee** [comment]
fixed by changing the model null handling
